### ISSUE TITLE
Not building with elm 0.16

### ISSUE THREAD

**Issue by tusj** [evancz/focus#4]
Hey, I am just trying out elm, and wanted to try out this package. Unfortunately, it seems that it is not entirely up to date. The package on package.elm-lang.org does not reflect the latest changes in the "elm-version" field in elm-package.json file. The latest commit says that 0.16 is supported, but it gives me an error message which made me think it's parser-related:

```
-- SYNTAX PROBLEM ---------------------------------------------- ./src/Focus.elm

I ran into something unexpected when parsing your code!

120│ (=>) largerFocus smallerFocus =
     ^
I am looking for one of the following things:

    end of input
    whitespace

Detected errors in 1 module. 
```

**Comment by evancz** [comment]
Just released an updated version to the package catalog. Can you try it out from there and let me know what happens?

**Comment by tusj** [comment]
Added the updated version and it works like a charm! Thanks so much.

2015-11-22 23:42 GMT+01:00 Evan Czaplicki notifications@github.com:
