### ISSUE TITLE
Link in README

### ISSUE THREAD

**Issue by altaic** [evancz/focus#7]
The "type-directed macros" link in the README.md requires permission to view. I don't know if this is intentional, but otherwise it'd be nice if it was freely viewable.

**Comment by michaelmesser** [comment]
Still requires permission to view

**Comment by evancz** [comment]
Added some notes about this in 0e4dff7c48b355279173f7f37287ca2ba0f8612a. I'd rather not share those designs anymore. I will bring them up again if they are on the near-term roadmap for some reason.
